DATASET_DIR = "dataset"
SHIPS_DATA_DIR = f"{DATASET_DIR}/Ships"
EQUIPMENT_DATA_DIR = f"{DATASET_DIR}/Equipments"
WEAPON_DATA_DIR = f"{DATASET_DIR}/Weapons"
ENGINEERING_DATA_DIR = f"{DATASET_DIR}/Engineering"
OUTPUT_DIR = "output"

ELITE_DANGEROUS_VECTOR_DB = "./elite_dangerous_llm_assistant.db"
COLLECTION_NAME = "rag_collection"

API_KEY = "MISTRAL_API_KEY"
AI_MODEL = "mistral-small-latest"
API_KEY_NOT_FOUND_ERROR = "API_KEY_NOT_FOUND_ERROR"
ELITE_HF_TOKEN = "ELITE_DANGEROUS_LLM_ASSISTANT_HF_TOKEN"