DATASET_DIR = "dataset"
SHIPS_DATA_DIR = f"{DATASET_DIR}/Ships"
EQUIPMENT_DATA_DIR = f"{DATASET_DIR}/Equipments"
WEAPON_DATA_DIR = f"{DATASET_DIR}/Weapons"
ENGINEERING_DATA_DIR = f"{DATASET_DIR}/Engineering"

RAW_DATA_FOLDER_NAME = "raw_data"

SHIPS_COLLECTION_NAME = "ships"

LOCAL_VECTOR_DB_FILE = "./astro-mind-vector.db"

ERROR_ENV_KEY_NOT_FOUND = "ERROR_ENV_KEY_NOT_FOUND"

TRANSFORM_LLM_PROVIDER = "TRANSFORM_LLM_PROVIDER"
TRANSFORM_LLM_API_KEY = "TRANSFORM_LLM_API_KEY"
TRANSFORM_LLM_MODEL = "TRANSFORM_LLM_MODEL"
TRANSFORM_LLM_URL = "TRANSFORM_LLM_URL"

EMBEDDER_LLM_PROVIDER="EMBEDDER_LLM_PROVIDER"
EMBEDDER_LLM_API_KEY="EMBEDDER_LLM_API_KEY"

INFERENCE_LLM_PROVIDER = "INFERENCE_LLM_PROVIDER"
INFERENCE_LLM_API_KEY = "INFERENCE_LLM_API_KEY"
INFERENCE_LLM_MODEL = "INFERENCE_LLM_MODEL"
INFERENCE_LLM_URL = "INFERENCE_LLM_URL"
